{
  "formatVersion": "1.1",
  "component": {
    "group": "Avif-Android",
    "module": "CustomProjectPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "groovy-plugin-1.0.0.jar",
          "url": "groovy-plugin-1.0.0.jar",
          "size": 40732,
          "sha512": "79002d48cbb34ba09c534225dc66151c424d34e4cfc25e6ce30773bcd0c5f15fff020cad47067a0b6415c23819ec85c5d71c9f8022c346722a6970948f5d2138",
          "sha256": "2a130ae600ab56d4fa0dc5c7824b4fedc7b7812b34ad54b783eb1d6b02d48571",
          "sha1": "627fb0aed56d17c051eaf3adea4ab8276f1a3c8f",
          "md5": "d70c8898d10eaa07107002191db2885a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          }
        }
      ],
      "files": [
        {
          "name": "groovy-plugin-1.0.0.jar",
          "url": "groovy-plugin-1.0.0.jar",
          "size": 40732,
          "sha512": "79002d48cbb34ba09c534225dc66151c424d34e4cfc25e6ce30773bcd0c5f15fff020cad47067a0b6415c23819ec85c5d71c9f8022c346722a6970948f5d2138",
          "sha256": "2a130ae600ab56d4fa0dc5c7824b4fedc7b7812b34ad54b783eb1d6b02d48571",
          "sha1": "627fb0aed56d17c051eaf3adea4ab8276f1a3c8f",
          "md5": "d70c8898d10eaa07107002191db2885a"
        }
      ]
    }
  ]
}
