{
  "formatVersion": "1.1",
  "component": {
    "group": "Avif-Android",
    "module": "CustomProjectPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-plugin-1.0.0.jar",
          "url": "android-plugin-1.0.0.jar",
          "size": 74099,
          "sha512": "a375dc7c0ab58fd4f822bf6b17199fbca92d31d5fa49a4d1bdae965ed89f2661113fec016828dd7035f110d44f8303acffc6c124bdbc6f88c291680248771dde",
          "sha256": "88e8f520de9b243840ee348da85d082d99af266e0d7a015feea6b3ec0d0f79d3",
          "sha1": "9618b8b10d88ac041e5ad92df812a29fc8caf280",
          "md5": "42f9d83447083e6322714d9847409bee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          }
        }
      ],
      "files": [
        {
          "name": "android-plugin-1.0.0.jar",
          "url": "android-plugin-1.0.0.jar",
          "size": 74099,
          "sha512": "a375dc7c0ab58fd4f822bf6b17199fbca92d31d5fa49a4d1bdae965ed89f2661113fec016828dd7035f110d44f8303acffc6c124bdbc6f88c291680248771dde",
          "sha256": "88e8f520de9b243840ee348da85d082d99af266e0d7a015feea6b3ec0d0f79d3",
          "sha1": "9618b8b10d88ac041e5ad92df812a29fc8caf280",
          "md5": "42f9d83447083e6322714d9847409bee"
        }
      ]
    }
  ]
}
