{
  "formatVersion": "1.1",
  "component": {
    "group": "Avif-Android",
    "module": "CustomProjectPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-plugin-1.0.0.jar",
          "url": "android-plugin-1.0.0.jar",
          "size": 65454,
          "sha512": "d2a9cde6725cd3f00d74b34b5ceb1533d9bdc5572b1e44ad9b1977defa65f33fd206d0f21e4b092ad0ba0200142dfed129839f5b070b62f323554ba4f66aedee",
          "sha256": "861111535805186d3874ac36ecfbf434bbcb0262e6008a2955a564cde47e7794",
          "sha1": "e2cce61d82d0b1c83225753606142b7c09406a1b",
          "md5": "785c87cafb864cd75a37b0baca68a603"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          }
        }
      ],
      "files": [
        {
          "name": "android-plugin-1.0.0.jar",
          "url": "android-plugin-1.0.0.jar",
          "size": 65454,
          "sha512": "d2a9cde6725cd3f00d74b34b5ceb1533d9bdc5572b1e44ad9b1977defa65f33fd206d0f21e4b092ad0ba0200142dfed129839f5b070b62f323554ba4f66aedee",
          "sha256": "861111535805186d3874ac36ecfbf434bbcb0262e6008a2955a564cde47e7794",
          "sha1": "e2cce61d82d0b1c83225753606142b7c09406a1b",
          "md5": "785c87cafb864cd75a37b0baca68a603"
        }
      ]
    }
  ]
}
