{
  "formatVersion": "1.1",
  "component": {
    "group": "Avif-Android",
    "module": "CustomProjectPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-plugin-1.0.0.jar",
          "url": "android-plugin-1.0.0.jar",
          "size": 74453,
          "sha512": "f0ad7a0d64b22a7453043c7f84032296459fb4d847b9b48e2a124298e187ee465df082e58d898cda03f88ddbc33f90cb97a307b13dac624018654ba33150dccb",
          "sha256": "a1b7d724ff86c0ecbc14b629faf973052b4fd78e0df5ba2076530e2ed7b3ae7e",
          "sha1": "40e5d05cc9746333835cdc626227077a89cf6e63",
          "md5": "cbf1dab8587f7afb5d381f6f50559312"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          }
        }
      ],
      "files": [
        {
          "name": "android-plugin-1.0.0.jar",
          "url": "android-plugin-1.0.0.jar",
          "size": 74453,
          "sha512": "f0ad7a0d64b22a7453043c7f84032296459fb4d847b9b48e2a124298e187ee465df082e58d898cda03f88ddbc33f90cb97a307b13dac624018654ba33150dccb",
          "sha256": "a1b7d724ff86c0ecbc14b629faf973052b4fd78e0df5ba2076530e2ed7b3ae7e",
          "sha1": "40e5d05cc9746333835cdc626227077a89cf6e63",
          "md5": "cbf1dab8587f7afb5d381f6f50559312"
        }
      ]
    }
  ]
}
